#!/bin/sh

ADDONNAME=hm-tools
ADDON_DIR=/usr/local/addons/hm-tools
PROFILE_DIR=/usr/local/etc/profile.d
WWW_DIR=/usr/local/etc/config/addons/www/hm-tools
# CONFIG_URL=/addons/hm-tools/

case "$1" in
""|start)
  ;;
info)
  echo "Info: <b>HM-Tools CCU Addon</b><br>"
  
  if [ -e $ADDON_DIR/bin/expect ]; then
    echo "Info: expect Version: 5.45.3<br>"
  fi
  if [ -e $ADDON_DIR/bin/mc ]; then
    echo "Info: midnight commander Version: 4.8.20<br>"
  fi
  if [ -e $ADDON_DIR/bin/nano ]; then
    echo "Info: nano Version: 2.8.7<br>"
  fi
  if [ -e $ADDON_DIR/bin/htop ]; then
    echo "Info: htop Version: 2.0.2<br>"
  fi
  if [ -e $ADDON_DIR/bin/bash ]; then
    echo "Info: bash Version: 4.4.12<br>"
  fi
  if [ -e $ADDON_DIR/bin/magick ]; then
    echo "Info: imagemagick Version: 7.0.7-10<br>"
  fi

  echo "Info: <br>"
  echo "Info: (c) 2017 Frank Hettrich<br>"
  echo "Info: <a href='https://github.com/fhetty/hm-tools'>https://github.com/fhetty/hm-tools</a>"
  echo "Version: $(cat ${ADDON_DIR}/VERSION)"
  echo "Name: HM-Tools<br>"
  echo "Operations: uninstall"
  echo "Update: /addons/${ADDONNAME}/update-check.cgi"
  ;;
uninstall)
  rm -rf $ADDON_DIR
  rm -rf $WWW_DIR
  rm -rf $PROFILE_DIR/hm-tools-addons.sh
  
  ;;
esac

exit 0
